// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Entities;
using Microsoft.EntityFrameworkCore;

namespace Repository;

public partial class ShopContext : DbContext
{

    public ShopContext(DbContextOptions<ShopContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CategoriesTbl> CategoriesTbls { get; set; }

    public virtual DbSet<ProductsTbl> ProductsTbls { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CategoriesTbl>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK_Categories");

            entity.ToTable("Categories_tbl");

            entity.Property(e => e.CategoryId).HasColumnName("Category_id");
            entity.Property(e => e.CategoryName).HasColumnName("Category_name");
        });

        modelBuilder.Entity<ProductsTbl>(entity =>
        {
            entity.HasKey(e => e.ProductId);

            entity.ToTable("Products_tbl");

            entity.Property(e => e.ProductId).HasColumnName("Product_id");
            entity.Property(e => e.CategoryId).HasColumnName("Category_id");
            entity.Property(e => e.ProductDescrebtion).HasColumnName("Product_descrebtion");
            entity.Property(e => e.ProductName).HasColumnName("Product_name");
            entity.Property(e => e.ProductPicture).HasColumnName("Product_picture");
            entity.Property(e => e.ProductPrice).HasColumnName("Product_price");

            entity.HasOne(d => d.Category).WithMany(p => p.ProductsTbls)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_Products_tbl_Categories_tbl");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.UserId).HasColumnName("User_id");
            entity.Property(e => e.FirstName).HasColumnName("First_name");
            entity.Property(e => e.LastName).HasColumnName("Last_name");
            entity.Property(e => e.Password).IsRequired();
            entity.Property(e => e.UserMail)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("User_mail");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}